# This workflow builds and run all tests on all platforms

name: Gradle Build and Tests

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    gradle:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-java@v1
              with:
                java-version: 1.8
            - name: Build with Gradle
              uses: gradle/gradle-build-action@v2
              with:
                arguments: build
            - name: Run all tests
              uses: gradle/gradle-build-action@v2
              with:
                arguments: allTests

